# Site settings
title:          Jackdm
description:    "a blog"
url:            "https://jackdm.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Jack McCoy
  url:          https://jackdm.com
  email:        jack@directmessagellc.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
paginator_path: "/posts/:num/"
# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
